"""Init service

Revision ID: aa1f75f1ce07
Revises: 
Create Date: 2024-10-04 12:33:32.546205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1f75f1ce07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_queues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s3_folder_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'FAILED', 'COMPLETED', name='filequeuestatus'), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_queues')
    # ### end Alembic commands ###
