"""Initial Setup

Revision ID: b799b904a867
Revises:
Create Date: 2025-07-09 19:31:09.396620

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b799b904a867"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "examples",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_examples_email"), "examples", ["email"], unique=True)
    op.create_index(op.f("ix_examples_id"), "examples", ["id"], unique=True)
    op.create_index(op.f("ix_examples_name"), "examples", ["name"], unique=False)
    op.create_table(
        "examples2",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("example_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["example_id"],
            ["examples.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_examples2_email"), "examples2", ["email"], unique=True)
    op.create_index(op.f("ix_examples2_id"), "examples2", ["id"], unique=True)
    op.create_index(op.f("ix_examples2_name"), "examples2", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_examples2_name"), table_name="examples2")
    op.drop_index(op.f("ix_examples2_id"), table_name="examples2")
    op.drop_index(op.f("ix_examples2_email"), table_name="examples2")
    op.drop_table("examples2")
    op.drop_index(op.f("ix_examples_name"), table_name="examples")
    op.drop_index(op.f("ix_examples_id"), table_name="examples")
    op.drop_index(op.f("ix_examples_email"), table_name="examples")
    op.drop_table("examples")
    # ### end Alembic commands ###
